$dsdl-version: "0.5.0"
$import:
    - class/cifar100-class-dom
    - task/cifar100-struct

meta:
    name: "CIFAR100"
    creator: "MSRA"
    dataset-version: "1.0.0"
    subdata-name: "train"

data:
    sample-type: Cifar100Sample[cdom0=Cifar100ImagesFineLabelClassificationClassDom,cdom1=Cifar100ImagesCoarseLabelClassificationClassDom]
    samples:
        - image: "media/000000000001.png"
          label0: apple.fruit_and_vegetables
          label1: fruit_and_vegetables
        - image: "media/000000000004.png"
          label0: aquarium_fish.fish
          label1: fish
        - image: "media/000000000002.png"
          label0: elephant.large_omnivores_and_herbivores
          label1: large_omnivores_and_herbivores
        - image: "media/000000000005.png"
          label0: cup.food_containers
          label1: food_containers
        - image: "media/000000000008.png"
          label0: telephone.household_electrical_devices
          label1: household_electrical_devices
        - image: "media/000000000003.png"
          label0: train.vehicles_1
          label1: vehicles_1
        - image: "media/000000000007.png"
          label0: cloud.large_natural_outdoor_scenes
          label1: large_natural_outdoor_scenes
        - image: "media/000000000000.png"
          label0: boy.people
          label1: people
        - image: "media/000000000009.png"
          label0: cattle.large_omnivores_and_herbivores
          label1: large_omnivores_and_herbivores
        - image: "media/000000000006.png"
          label0: dinosaur.reptiles
          label1: reptiles
